### ISSUE TITLE
Commands shows error in console

### ISSUE THREAD

**Issue by Sunriz3D** [fritzr/discord-twitter-bot#1]
Hey, 

`@Bot $info` 
give me the following

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 540, in dispatch
    getattr(self, event_method, utils._null_event)(*args, **kwargs)
  File "DiscordTwitterBot.py", line 375, in on_message
    self.send_message(message.channel, self.info(message.channel), False)
  File "DiscordTwitterBot.py", line 345, in info
    for u in self.mentions[channel.id]:
KeyError: '143890089880190977'
```

The bot is active in a text channel, `@Bot $help` works, following too ( but the live feed don't show up ).

**Comment by fritzr** [comment]
Did you $addchannel first?

**Comment by Sunriz3D** [comment]
Yep

**Comment by fritzr** [comment]
Fixed in the latest commit e10b53a8a9ec9ebf87f9ec410e5f6cfee884f392

**Comment by Sunriz3D** [comment]
When i follow someone on discord I got this in console output 

`Twitter Error: [420] b'Exceeded connection limit for user\r\n'
Twitter Error: [420] Unable to decode response,                                       not valid JSON.
Twitter Error: [420] b'Exceeded connection limit for user\r\n'
Twitter Error: [420] Unable to decode response,                                       not valid JSON.
Twitter Error: [420] b'Exceeded connection limit for user\r\n'
Maximum number of errors exceeded, disconnecting...
`

**Comment by fritzr** [comment]
Do you have multiple copies of the program running at once? You are only allowed a very few number of open connections to Twitter at a time. If you don't close out of the program properly, you may have several running in the background.

**Comment by Sunriz3D** [comment]
No just this one is using twitter connections

**Comment by fritzr** [comment]
You are also limited to 150 requests per hour and 15 connections per 15 minutes. If you're tweeting a lot or restarting the program a lot you may also be rate limited. Try again in an hour and see if it still happens.
