### ISSUE TITLE
No tweets streamed

### ISSUE THREAD

**Issue by Sunriz3D** [fritzr/discord-twitter-bot#2]
Hey its me again,

so the connection is working, I followed myself to test the bot.

But when I tweet nothing is streamed to Discord.
When I do `@Bot $info` it shows correctly (time/date) the last tweet from user.

And I got another error : 

> received data: {'delete': {'timestamp_ms': '1454432205290', 'status': {'user_id_str': '780419844', 'id_str': '694565019925778432', 'user_id': 780419844, 'id': 694565019925778432}}}
> received data: {'lang': 'en', 'contributors': None, 'retweeted': False, 'geo': None, 'id_str': '694565171063320577', 'place': None, 'id': 694565171063320577, 'is_quote_status': False, 'entities': {'user_mentions': [], 'urls': [], 'symbols': [], 'hashtags': [{'indices': [5, 12], 'text': 'sunbot'}]}, 'retweet_count': 0, 'user': {'lang': 'fr', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/378800000279673168/1470da582eb025f2ebb7892b614f1abf_normal.jpeg', 'url': None, 'screen_name': 'Sunriz3D', 'profile_use_background_image': True, 'time_zone': 'Paris', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'listed_count': 1, 'geo_enabled': True, 'id_str': '780419844', 'profile_link_color': '0084B4', 'utc_offset': 3600, 'followers_count': 23, 'default_profile_image': False, 'id': 780419844, 'created_at': 'Sat Aug 25 14:31:29 +0000 2012', 'profile_image_url': 'http://pbs.twimg.com/profile_images/378800000279673168/1470da582eb025f2ebb7892b614f1abf_normal.jpeg', 'name': 'Sunriz3D', 'contributors_enabled': False, 'location': 'Paris', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/780419844/1436534089', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'default_profile': True, 'notifications': None, 'favourites_count': 57, 'profile_background_color': 'C0DEED', 'following': None, 'protected': False, 'friends_count': 246, 'statuses_count': 53, 'is_translator': False, 'profile_background_tile': False, 'verified': False, 'description': 'http://sunriz3d.ovh', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'follow_request_sent': None, 'profile_sidebar_border_color': 'C0DEED'}, 'in_reply_to_screen_name': None, 'in_reply_to_status_id': None, 'truncated': False, 'in_reply_to_user_id': None, 'timestamp_ms': '1454432215835', 'source': '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>', 'in_reply_to_status_id_str': None, 'in_reply_to_user_id_str': None, 'coordinates': None, 'text': 'test #sunbot', 'favorited': False, 'filter_level': 'low', 'created_at': 'Tue Feb 02 16:56:55 +0000 2016', 'favorite_count': 0}
> Exception in thread Thread-5:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/threading.py", line 923, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.5/threading.py", line 871, in run
>     self._target(*self._args, **self._kwargs)
>   File "DiscordTwitterBot.py", line 189, in follow
>     self.statuses.filter(follow=uid)
>   File "/usr/local/lib/python3.5/site-packages/twython/streaming/types.py", line 66, in filter
>     self.streamer._request(url, 'POST', params=params)
>   File "/usr/local/lib/python3.5/site-packages/twython/streaming/api.py", line 154, in _request
>     if self.on_success(data):  # pragma: no cover
>   File "DiscordTwitterBot.py", line 262, in on_success
>     callback(data)
>   File "DiscordTwitterBot.py", line 512, in tweet
>     self.send_all(msg, mention)
>   File "DiscordTwitterBot.py", line 307, in send_all
>     mention = self.mentions[chan.id]
> KeyError: '143892468306280448'

**Comment by fritzr** [comment]
Hey yeah actually I just noticed that bug a few minutes ago and fixed it in 7f30e640de657a5e37e753a4f9e77f39f4d4853d. Run the latest revision, it should work fine.
