### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Sunriz3D** [fritzr/discord-twitter-bot#3]
Hey, the tweet streaming are working until a moment where I got this error : 

> Status': False, 'user': {'url': 'https://support.bladeandsoul.com/hc/en-us', 'following': None, 'default_profile_image': False, 'profile_text_color': '333333', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/655164370347950080/ykOuzFOD_normal.jpg', 'id': 3521186773, 'id_str': '3521186773', 'protected': False, 'time_zone': 'Pacific Time (US & Canada)', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/3521186773/1445038341', 'listed_count': 56, 'utc_offset': -28800, 'is_translator': False, 'description': "This is the official Blade & Soul Operations/Support Twitter. We'll be dishing out server status and Support Assistance.", 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'lang': 'en', 'profile_background_tile': False, 'favourites_count': 0, 'created_at': 'Fri Sep 11 00:47:04 +0000 2015', 'profile_link_color': '0084B4', 'friends_count': 14, 'profile_sidebar_fill_color': 'DDEEF6', 'profile_sidebar_border_color': 'C0DEED', 'contributors_enabled': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/655164370347950080/ykOuzFOD_normal.jpg', 'profile_background_color': 'C0DEED', 'location': 'Aliso Viejo, CA', 'geo_enabled': False, 'followers_count': 29013, 'verified': False, 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'screen_name': 'BladeAndSoulOps', 'name': 'Blade & Soul Ops', 'statuses_count': 4652, 'default_profile': True, 'notifications': None, 'follow_request_sent': None, 'profile_use_background_image': True}, 'created_at': 'Fri Feb 05 02:39:34 +0000 2016', 'in_reply_to_status_id': 695422064996397066, 'coordinates': None, 'retweet_count': 0, 'favorited': False, 'in_reply_to_screen_name': 'HeggiexDoWx', 'source': '<a href="http://www.hootsuite.com" rel="nofollow">Hootsuite</a>', 'timestamp_ms': '1454639974164', 'favorite_count': 0, 'truncated': False, 'filter_level': 'low', 'lang': 'en', 'in_reply_to_user_id_str': '2247957529', 'in_reply_to_status_id_str': '695422064996397066'}
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/threading.py", line 923, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.5/threading.py", line 871, in run
>     self._target(*self._args, **self._kwargs)
>   File "DiscordTwitterBot.py", line 189, in follow
>     self.statuses.filter(follow=uid)
>   File "/usr/local/lib/python3.5/site-packages/twython/streaming/types.py", line 66, in filter
>     self.streamer._request(url, 'POST', params=params)
>   File "/usr/local/lib/python3.5/site-packages/twython/streaming/api.py", line 154, in _request
>     if self.on_success(data):  # pragma: no cover
>   File "DiscordTwitterBot.py", line 251, in on_success
>     print("received data:", data)
> UnicodeEncodeError: 'ascii' codec can't encode character '\u2726' in position 263: ordinal not in range(128)

**Comment by fritzr** [comment]
Fixed in df33b3a67ce4f8d100ec699d232bf7e4332f1d73
